"""
Bitcoin Arbitrage Strategy - Coinbase WebSocket Client
Detects price movements and generates BUY_YES/BUY_NO signals for Polymarket
"""
import json
import logging
import queue
import threading
import time
import websocket
from datetime import datetime, timedelta
from decimal import Decimal
from enum import Enum
from typing import Optional, Dict, Any, Callable, List
from dataclasses import dataclass, field
from collections import deque

from config.strategy_config import arbitrage_config
from trader.clob_trader import ClobTrader

logger = logging.getLogger(__name__)


class Signal(Enum):
    """Trading signals generated by the strategy"""
    BUY_YES = "BUY_YES"
    BUY_NO = "BUY_NO"
    HOLD = "HOLD"
    SELL = "SELL"


@dataclass
class PricePoint:
    """Single price data point"""
    price: float
    timestamp: datetime
    volume: float = 0.0
    
    def __repr__(self):
        return f"PricePoint(price={self.price:.2f}, time={self.timestamp.strftime('%H:%M:%S')})"


@dataclass
class Position:
    """Active trading position"""
    entry_price: float
    size: float
    side: str  # 'YES' or 'NO'
    entry_time: datetime
    signal: Signal
    market_slug: str = "bitcoin-arbitrage"
    
    def current_pnl(self, current_price: float) -> float:
        """Calculate current PnL percentage"""
        if self.side == 'YES':
            return (current_price - self.entry_price) / self.entry_price
        else:  # NO
            return (self.entry_price - current_price) / self.entry_price
    
    def should_exit(self, current_price: float) -> tuple[bool, str]:
        """Check if position should be closed"""
        pnl = self.current_pnl(current_price)
        
        # Profit target reached
        if pnl >= arbitrage_config.PROFIT_TARGET:
            return True, f"Profit target reached: {pnl:.2%}"
        
        # Stop loss hit
        if pnl <= -arbitrage_config.STOP_LOSS:
            return True, f"Stop loss hit: {pnl:.2%}"
        
        # Timeout check
        elapsed = (datetime.now() - self.entry_time).total_seconds()
        if elapsed >= arbitrage_config.STOP_LOSS_TIMEOUT:
            return True, f"Timeout: {elapsed:.0f}s elapsed"
        
        return False, ""


@dataclass
class TradeSignal:
    """Complete trade signal with metadata"""
    signal: Signal
    price: float
    change_pct: float
    timestamp: datetime
    confidence: float = 0.0  # 0-1 confidence score
    reason: str = ""


class PriceHistory:
    """Thread-safe price history buffer"""
    
    def __init__(self, max_size: int = 100):
        self._prices: deque = deque(maxlen=max_size)
        self._lock = threading.Lock()
    
    def add(self, price_point: PricePoint):
        """Add new price point"""
        with self._lock:
            self._prices.append(price_point)
    
    def get_last(self, n: int = 1) -> List[PricePoint]:
        """Get last n price points"""
        with self._lock:
            return list(self._prices)[-n:] if n <= len(self._prices) else list(self._prices)
    
    def get_all(self) -> List[PricePoint]:
        """Get all price points"""
        with self._lock:
            return list(self._prices)
    
    def get_average(self, n: int = 10) -> Optional[float]:
        """Get average of last n prices"""
        with self._lock:
            if len(self._prices) < n:
                return None
            recent = list(self._prices)[-n:]
            return sum(p.price for p in recent) / len(recent)
    
    def get_volatility(self, n: int = 20) -> Optional[float]:
        """Calculate volatility (standard deviation) of last n prices"""
        with self._lock:
            if len(self._prices) < n:
                return None
            recent = list(self._prices)[-n:]
            prices = [p.price for p in recent]
            avg = sum(prices) / len(prices)
            variance = sum((p - avg) ** 2 for p in prices) / len(prices)
            return variance ** 0.5 / avg if avg > 0 else 0  # Coefficient of variation
    
    def clear(self):
        """Clear all price history"""
        with self._lock:
            self._prices.clear()
    
    def __len__(self):
        with self._lock:
            return len(self._prices)


class BitcoinArbitrageStrategy:
    """
    Bitcoin Arbitrage Strategy
    
    Detects price movements on Coinbase and generates trading signals
    for Polymarket Bitcoin prediction markets.
    """
    
    def __init__(self, trader: Optional[ClobTrader] = None):
        """
        Initialize the strategy
        
        Args:
            trader: ClobTrader instance for executing trades
        """
        self.trader = trader
        self.price_history = PriceHistory(max_size=arbitrage_config.PRICE_HISTORY_SIZE)
        self.signal_queue: queue.Queue[TradeSignal] = queue.Queue()
        
        # Position tracking
        self.active_position: Optional[Position] = None
        self.daily_trades: int = 0
        self.last_trade_time: Optional[datetime] = None
        self.daily_reset_time: datetime = datetime.now().replace(hour=0, minute=0, second=0)
        
        # Statistics
        self.stats = {
            'signals_generated': 0,
            'trades_executed': 0,
            'trades_successful': 0,
            'total_pnl': 0.0,
            'last_signal': None,
            'last_price': None,
            'price_change_24h': 0.0
        }
        
        # Running state
        self._running = False
        self._thread: Optional[threading.Thread] = None
        
        logger.info("BitcoinArbitrageStrategy initialized")
    
    def on_price_update(self, price: float, volume: float = 0.0) -> Optional[TradeSignal]:
        """
        Process new price update and generate signal
        
        Args:
            price: Current BTC price in USD
            volume: Trading volume (optional)
            
        Returns:
            TradeSignal if a signal is generated, None otherwise
        """
        # Create price point
        price_point = PricePoint(
            price=price,
            timestamp=datetime.now(),
            volume=volume
        )
        
        # Add to history
        self.price_history.add(price_point)
        self.stats['last_price'] = price
        
        # Check if we have enough history
        if len(self.price_history) < 10:
            logger.debug(f"Building price history: {len(self.price_history)}/10 points")
            return None
        
        # Check cooldown
        if self.last_trade_time:
            cooldown_elapsed = (datetime.now() - self.last_trade_time).total_seconds()
            if cooldown_elapsed < arbitrage_config.COOLDOWN_SECONDS:
                if arbitrage_config.VERBOSE_LOGGING:
                    logger.debug(f"Cooldown active: {cooldown_elapsed:.0f}s / {arbitrage_config.COOLDOWN_SECONDS}s")
                return None
        
        # Check daily limit
        self._reset_daily_counter_if_needed()
        if self.daily_trades >= arbitrage_config.MAX_DAILY_TRADES:
            if arbitrage_config.VERBOSE_LOGGING:
                logger.debug(f"Daily trade limit reached: {self.daily_trades}/{arbitrage_config.MAX_DAILY_TRADES}")
            return None
        
        # Calculate price change
        signal = self._calculate_signal(price)
        
        if signal.signal != Signal.HOLD:
            self.stats['signals_generated'] += 1
            self.signal_queue.put(signal)
            self.stats['last_signal'] = signal
            
            logger.info(
                f"🚨 SIGNAL: {signal.signal.value} | "
                f"Price: ${price:,.2f} | Change: {signal.change_pct:+.2%} | "
                f"Confidence: {signal.confidence:.1%} | {signal.reason}"
            )
        
        return signal if signal.signal != Signal.HOLD else None
    
    def _calculate_signal(self, current_price: float) -> TradeSignal:
        """
        Calculate trading signal based on price movement
        
        Args:
            current_price: Current BTC price
            
        Returns:
            TradeSignal with decision
        """
        # Get reference prices
        last_price = self.price_history.get_last(1)[0].price
        avg_10 = self.price_history.get_average(10)
        avg_50 = self.price_history.get_average(min(50, len(self.price_history)))
        volatility = self.price_history.get_volatility(20) or 0.001
        
        # Calculate changes
        change_from_last = (current_price - last_price) / last_price if last_price > 0 else 0
        change_from_avg_10 = (current_price - avg_10) / avg_10 if avg_10 else 0
        change_from_avg_50 = (current_price - avg_50) / avg_50 if avg_50 else 0
        
        # Dynamic threshold based on volatility
        dynamic_threshold = max(arbitrage_config.ARBITRAGE_THRESHOLD, volatility * 1.5)
        
        # Generate signal based on momentum
        signal = Signal.HOLD
        confidence = 0.0
        reason = ""
        
        # Strong upward momentum - BUY YES (Bitcoin goes up)
        if change_from_avg_10 > dynamic_threshold and change_from_last > 0:
            signal = Signal.BUY_YES
            confidence = min(abs(change_from_avg_10) / (dynamic_threshold * 2), 1.0)
            reason = f"Upward momentum: {change_from_avg_10:+.2%} > threshold {dynamic_threshold:.2%}"
        
        # Strong downward momentum - BUY NO (Bitcoin goes down)
        elif change_from_avg_10 < -dynamic_threshold and change_from_last < 0:
            signal = Signal.BUY_NO
            confidence = min(abs(change_from_avg_10) / (dynamic_threshold * 2), 1.0)
            reason = f"Downward momentum: {change_from_avg_10:+.2%} < threshold -{dynamic_threshold:.2%}"
        
        # Mean reversion signal
        elif abs(change_from_avg_50) > dynamic_threshold * 2 and abs(change_from_avg_10) < volatility:
            if change_from_avg_50 > 0:
                signal = Signal.BUY_NO  # Overbought, expect reversion
                confidence = 0.5
                reason = "Mean reversion: price far above 50-period average"
            else:
                signal = Signal.BUY_YES  # Oversold, expect reversion
                confidence = 0.5
                reason = "Mean reversion: price far below 50-period average"
        
        return TradeSignal(
            signal=signal,
            price=current_price,
            change_pct=change_from_avg_10,
            timestamp=datetime.now(),
            confidence=confidence,
            reason=reason
        )
    
    def execute_signal(self, signal: TradeSignal) -> bool:
        """
        Execute trade based on signal
        
        Args:
            signal: TradeSignal to execute
            
        Returns:
            True if trade was executed successfully
        """
        if not self.trader or not self.trader.initialized:
            logger.warning("No trader available, cannot execute signal")
            return False
        
        # Close existing position if opposite signal
        if self.active_position:
            should_close = False
            if self.active_position.side == 'YES' and signal.signal == Signal.BUY_NO:
                should_close = True
            elif self.active_position.side == 'NO' and signal.signal == Signal.BUY_YES:
                should_close = True
            
            if should_close:
                logger.info(f"Closing existing {self.active_position.side} position due to opposite signal")
                self._close_position(signal.price)
        
        # Don't open new position if we already have one
        if self.active_position:
            logger.debug(f"Already have active position: {self.active_position.side}")
            return False
        
        # Determine position parameters
        if signal.signal == Signal.BUY_YES:
            side = 'YES'
            outcome = 'Yes'
        elif signal.signal == Signal.BUY_NO:
            side = 'NO'
            outcome = 'No'
        else:
            return False
        
        # Calculate position size based on confidence
        base_size = arbitrage_config.MAX_POSITION_SIZE
        size = base_size * (0.5 + signal.confidence * 0.5)  # Scale 50%-100% based on confidence
        size = max(size, arbitrage_config.MIN_POSITION_SIZE)
        size = round(size, 2)
        
        # Find Bitcoin market on Polymarket
        market_slug = self._find_bitcoin_market()
        if not market_slug:
            logger.error("No suitable Bitcoin market found on Polymarket")
            return False
        
        logger.info(f"Executing {side} position: ${size} on {market_slug}")
        
        # Create order
        success, error, result = self.trader.create_order(
            market_slug=market_slug,
            outcome=outcome,
            side='BUY',
            size=size
        )
        
        if success:
            self.active_position = Position(
                entry_price=signal.price,
                size=size,
                side=side,
                entry_time=datetime.now(),
                signal=signal.signal,
                market_slug=market_slug
            )
            self.daily_trades += 1
            self.last_trade_time = datetime.now()
            self.stats['trades_executed'] += 1
            
            logger.info(f"✅ Trade executed successfully: {result.get('order_id', 'unknown')}")
            return True
        else:
            logger.error(f"❌ Trade execution failed: {error}")
            return False
    
    def _close_position(self, current_price: float) -> bool:
        """
        Close active position
        
        Args:
            current_price: Current BTC price for PnL calculation
            
        Returns:
            True if position was closed
        """
        if not self.active_position:
            return False
        
        if not self.trader or not self.trader.initialized:
            logger.warning("No trader available, cannot close position")
            return False
        
        # Calculate PnL
        pnl = self.active_position.current_pnl(current_price)
        self.stats['total_pnl'] += pnl
        
        # Determine closing side
        close_outcome = 'Yes' if self.active_position.side == 'YES' else 'No'
        
        logger.info(
            f"Closing {self.active_position.side} position | "
            f"PnL: {pnl:+.2%} | Entry: ${self.active_position.entry_price:,.2f} | "
            f"Exit: ${current_price:,.2f}"
        )
        
        # Execute close order (sell our position)
        success, error, result = self.trader.create_order(
            market_slug=self.active_position.market_slug,
            outcome=close_outcome,
            side='SELL',
            size=self.active_position.size
        )
        
        if success:
            self.active_position = None
            self.stats['trades_successful'] += 1
            logger.info("✅ Position closed successfully")
            return True
        else:
            logger.error(f"❌ Failed to close position: {error}")
            return False
    
    def _find_bitcoin_market(self) -> Optional[str]:
        """
        Find a suitable Bitcoin prediction market on Polymarket
        
        Returns:
            Market slug or None
        """
        # Common Bitcoin market slugs on Polymarket
        bitcoin_markets = [
            "will-bitcoin-hit-100k-in-2024",
            "will-bitcoin-hit-90000-before-december-31",
            "will-bitcoin-be-above-60000-on-december-31",
            "bitcoin-all-time-high-2024",
        ]
        
        if not self.trader or not self.trader.initialized:
            return None
        
        for slug in bitcoin_markets:
            market = self.trader.validate_market(slug)
            if market:
                return slug
        
        return None
    
    def check_position(self, current_price: float):
        """
        Check active position for exit conditions
        
        Args:
            current_price: Current BTC price
        """
        if not self.active_position:
            return
        
        should_exit, reason = self.active_position.should_exit(current_price)
        
        if should_exit:
            logger.info(f"Exit condition met: {reason}")
            self._close_position(current_price)
    
    def _reset_daily_counter_if_needed(self):
        """Reset daily trade counter if it's a new day"""
        current_time = datetime.now()
        if current_time.date() != self.daily_reset_time.date():
            logger.info(f"New day detected, resetting daily trade counter (was: {self.daily_trades})")
            self.daily_trades = 0
            self.daily_reset_time = current_time
    
    def get_stats(self) -> Dict[str, Any]:
        """Get strategy statistics"""
        stats = self.stats.copy()
        stats['price_history_length'] = len(self.price_history)
        stats['active_position'] = self.active_position
        stats['daily_trades'] = self.daily_trades
        stats['daily_limit'] = arbitrage_config.MAX_DAILY_TRADES
        return stats
    
    def start(self):
        """Start the strategy processing loop"""
        self._running = True
        self._thread = threading.Thread(target=self._process_signals, daemon=True)
        self._thread.start()
        logger.info("BitcoinArbitrageStrategy started")
    
    def stop(self):
        """Stop the strategy"""
        self._running = False
        if self._thread:
            self._thread.join(timeout=5)
        logger.info("BitcoinArbitrageStrategy stopped")
    
    def _process_signals(self):
        """Background thread to process signals from queue"""
        while self._running:
            try:
                # Get signal with timeout
                signal = self.signal_queue.get(timeout=1)
                self.execute_signal(signal)
            except queue.Empty:
                continue
            except Exception as e:
                logger.error(f"Error processing signal: {e}")


class CoinbaseWebSocketClient:
    """
    Coinbase WebSocket Client for real-time BTC price data
    """
    
    def __init__(self, strategy: BitcoinArbitrageStrategy):
        """
        Initialize WebSocket client
        
        Args:
            strategy: BitcoinArbitrageStrategy instance to feed price data
        """
        self.strategy = strategy
        self.ws: Optional[websocket.WebSocketApp] = None
        self._running = False
        self._thread: Optional[threading.Thread] = None
        self.reconnect_delay = arbitrage_config.WS_RECONNECT_DELAY
        self.last_heartbeat = datetime.now()
        
        logger.info("CoinbaseWebSocketClient initialized")
    
    def _on_message(self, ws, message):
        """Handle incoming WebSocket message"""
        try:
            data = json.loads(message)
            
            if data.get('type') == 'ticker':
                price = float(data.get('price', 0))
                volume = float(data.get('volume_24h', 0))
                
                if price > 0:
                    # Feed to strategy
                    signal = self.strategy.on_price_update(price, volume)
                    
                    # Check active position
                    self.strategy.check_position(price)
                    
                    if arbitrage_config.VERBOSE_LOGGING and not signal:
                        logger.debug(f"BTC Price: ${price:,.2f} | 24h Vol: ${volume:,.0f}")
            
            elif data.get('type') == 'heartbeat':
                self.last_heartbeat = datetime.now()
                if arbitrage_config.VERBOSE_LOGGING:
                    logger.debug("Heartbeat received")
                    
        except json.JSONDecodeError as e:
            logger.error(f"Failed to parse message: {e}")
        except Exception as e:
            logger.error(f"Error processing message: {e}")
    
    def _on_error(self, ws, error):
        """Handle WebSocket error"""
        logger.error(f"WebSocket error: {error}")
    
    def _on_close(self, ws, close_status_code, close_msg):
        """Handle WebSocket close"""
        logger.warning(f"WebSocket closed: {close_status_code} - {close_msg}")
        self._running = False
        
        # Auto-reconnect
        if not getattr(self, '_stop_requested', False):
            logger.info(f"Reconnecting in {self.reconnect_delay}s...")
            time.sleep(self.reconnect_delay)
            self.start()
    
    def _on_open(self, ws):
        """Handle WebSocket open"""
        logger.info("✅ WebSocket connected to Coinbase")
        
        # Subscribe to ticker channel
        subscribe_msg = {
            "type": "subscribe",
            "product_ids": [arbitrage_config.COINBASE_PRODUCT_ID],
            "channels": ["ticker", "heartbeat"]
        }
        ws.send(json.dumps(subscribe_msg))
        logger.info(f"Subscribed to {arbitrage_config.COINBASE_PRODUCT_ID} ticker")
    
    def start(self):
        """Start WebSocket connection"""
        if self._running:
            return
        
        self._running = True
        self._stop_requested = False
        
        # Create WebSocket app
        self.ws = websocket.WebSocketApp(
            arbitrage_config.COINBASE_WS_URL,
            on_open=self._on_open,
            on_message=self._on_message,
            on_error=self._on_error,
            on_close=self._on_close
        )
        
        # Start in background thread
        self._thread = threading.Thread(target=self._run, daemon=True)
        self._thread.start()
        
        logger.info(f"Connecting to Coinbase WebSocket: {arbitrage_config.COINBASE_WS_URL}")
    
    def _run(self):
        """Run WebSocket connection with auto-reconnect"""
        while self._running:
            try:
                self.ws.run_forever()
            except Exception as e:
                logger.error(f"WebSocket run error: {e}")
            
            if self._running and not self._stop_requested:
                logger.info(f"Reconnecting in {self.reconnect_delay}s...")
                time.sleep(self.reconnect_delay)
    
    def stop(self):
        """Stop WebSocket connection"""
        self._stop_requested = True
        self._running = False
        
        if self.ws:
            self.ws.close()
        
        if self._thread:
            self._thread.join(timeout=5)
        
        logger.info("CoinbaseWebSocketClient stopped")
    
    def is_connected(self) -> bool:
        """Check if WebSocket is connected"""
        return self._running and self.ws and self.ws.sock and self.ws.sock.connected


def create_bitcoin_arbitrage_strategy(trader: Optional[ClobTrader] = None) -> tuple[BitcoinArbitrageStrategy, CoinbaseWebSocketClient]:
    """
    Factory function to create strategy and WebSocket client
    
    Args:
        trader: Optional ClobTrader for executing trades
        
    Returns:
        Tuple of (strategy, websocket_client)
    """
    strategy = BitcoinArbitrageStrategy(trader=trader)
    ws_client = CoinbaseWebSocketClient(strategy)
    return strategy, ws_client
